### ISSUE TITLE
Unable to Download Content

### ISSUE THREAD

**Issue by Saibonizer** [iAmMe27/WoD#10]
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download BT3-Jan2023-R1.zip (GoogleDriveDownloader+State|1MF-RxZgrO0GFf3-_zUxB-0gAR2H1oFoW)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCworkshop03 - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcworkshop03 - voices_en.ba2)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCRobot - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcrobot - voices_en.ba2)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4_Default.ini (GameFileSourceDownloader+State|Fallout4|1.10.163.0|fallout4_default.ini)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCCoast - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlccoast - voices_en.ba2)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Voices.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - voices.ba2)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCNukaWorld - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcnukaworld - voices_en.ba2)
00:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by iAmMe27** [comment]
Verify your FO4 install on Steam.

**Comment by Saibonizer** [comment]
Ok i will do so, but the following file is a google drive file right? Can you reupload it?

0:00:32.094 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download BT3-Jan2023-R1.zip (GoogleDriveDownloader+State|1MF-RxZgrO0GFf3-_zUxB-0gAR2H1oFoW)

**Comment by iAmMe27** [comment]
I cannot reupload it. Please check the GitHub Wiki for a list of non-Nexus mods.

**Comment by Saibonizer** [comment]
Thats It. Thank you
