### ISSUE TITLE
AAF nuka ride 6.1.1 not avaible

### ISSUE THREAD

**Issue by lampyr** [iAmMe27/WoD#11]
Hello i wanted to try your modpack but i am stuck because of the AAF nuka ride.
![Capture d’écran 2023-05-16 202538](https://github.com/iAmMe27/WoD/assets/7419371/cc9162d8-4f1a-4bc1-8d3c-b3d67f66a88a)

and for the rest i don't know at the moment.

**Comment by iAmMe27** [comment]
Hello, I am aware of this issue but this means WoD is currently not installable. I am working on the next update but I have no solid ETA for it yet.
