### ISSUE TITLE
THESE ARE IN THE DOWNLOADS FOLDER NOTICE THEY ARE NEXUS LINKS

### ISSUE THREAD

**Issue by rogerthat33** [iAmMe27/WoD#15]
[Wabbajack.current.log](https://github.com/iAmMe27/WoD/files/11871055/Wabbajack.current.log)

**Comment by iAmMe27** [comment]
If you are experiencing issues with Nexus downloads, please try switching your preferred Nexus download server to something close to your location in the account settings.

You can access this area by clicking on your account in the top right, and selecting site preferences.

![image](https://github.com/iAmMe27/WoD/assets/98499526/65b8940f-ac9d-446a-a8b3-460abd2179b5)
