### ISSUE TITLE
CTD when loading from alternate start into commonwealth

### ISSUE THREAD

**Issue by Guttercookie** [iAmMe27/WoD#17]
i left it on the first profile in MO2, touched nothing. launched with the run button, waited for the game to load into the main menu, started a new game, and after choosing a charatcer preset, (and waiting for notifications to end) started putting together my alternate start. when finished, it started loading, and after about 20 secconds, it CTDs. no crash report in the files, either.

**Comment by iAmMe27** [comment]
You’d probably be best to join the Discord server for this issue.

I would think it’s either your antivirus interfering with the game/MO2s virtual file system or it’s a page file issue.
