### ISSUE TITLE
Error downloading mods

### ISSUE THREAD

**Issue by Wolfriptide** [iAmMe27/WoD#3]
At first it was 2 issues "FusionGirl" and "Bt3-Jan2023-R1" but i could manually download fusion girl, even looking in the archive i have no idea what mod to install for bt3

**Comment by iAmMe27** [comment]
You posted the file name that you want to download in your issue.

Please read the Installation section of the readme for a link to a list of all non-Nexus mods. FusionGirl and BT3 are both under the Google Drive files section.
