### ISSUE TITLE
hashing issue

### ISSUE THREAD

**Issue by NihlusCreed** [iAmMe27/WoD#7]
hay man im getting a hashing issue (reported as "AAAAAAAA" instead of their expected hash) with 2 mods ("Raider Dismember Replacer Male" and "AAF Spectators v1.3.7z")

**Comment by iAmMe27** [comment]
I’d recommend you download the mods manually in your browser. Check the GitHub Wiki for links and file names that you need.

**Comment by NihlusCreed** [comment]
I tried that but the same issue comes up... i shutdown wabba then did a manual download, placed the files with the rest then started wabba again and bam, it then again asks me to download the same files i just placed in the mod folder and shortly afterwards the same hashing issue occurs... this happens in both cases of allowing wabba to download it or downloading it manually (i make sure to delete the files before attempting ether option) please help me bro T_T out of all the mods its just these 2 and i have a  40 Mbps line it was pure pain to download them all lol

**Comment by iAmMe27** [comment]
If you manually downloaded the correct versions and placed them into the same folder you told WJ to download into, there's no reason WJ won't detect the files and hash them correctly. If there are similar file names with a large string of letters and numbers at the end of the name in your download folder, delete those.

Failing that, I would suggest performing a Wabbajack reset by following the below:

To completely reset your Wabbajack settings, start off by closing Wabbajack if it is open. Afterwards, press Windows + R on your keyboard and type in %localappdata%.

You should see a Windows Explorer window pop-up; find and delete the folder called Wabbajack.

**Comment by NihlusCreed** [comment]
![Screenshot 2023-05-01 131759](https://user-images.githubusercontent.com/112879309/235444891-501999e5-6e67-471f-99b6-6883787f021a.png)
i followed your steps to reset wabba but unfortunately im still getting the same error

**Comment by iAmMe27** [comment]
Have you tried deleting those files and replacing? 
Making sure your download and WJ folder are excluded from your antivirus?

**Comment by NihlusCreed** [comment]
nope still nothing... ok im going to go ham quickly and delete everything including the game and mods, im gonna borrow a friends fibre line and download it all again and start from scratch... if the issue comes up again ill let you know but it may take a while about an hour or 2

**Comment by iAmMe27** [comment]
Ok, here’s hoping.

I’ve never had this issue before so I’m starting to run out of ideas. Maybe join the Discord and see if others have run into this before?

**Comment by NihlusCreed** [comment]
![image](https://user-images.githubusercontent.com/112879309/235454540-c2b1dc19-0e1c-49d2-ac19-b84d81ddcff4.png)
![image](https://user-images.githubusercontent.com/112879309/235454595-8ef26dea-de60-4a5f-93c4-4280e2626dbd.png)
[Wabbajack.current.log](https://github.com/iAmMe27/WoD/files/11365415/Wabbajack.current.log)
ok so i got some progress after a clean install and manually downloading all the loverslab files i get this for 2 different files... something to do with google drive and these 2 mods "fusiongirl-0223.7z" and "BT3-jan2023-R1.zip" (no idea what bt3 is)

**Comment by iAmMe27** [comment]
Both of those are on the Wiki too, under Google Drive files.

**Comment by NihlusCreed** [comment]
Mate it seems my troubles are now over XD +++Respect for that incredible response speed and for the help you gave me Thank you man XD have an amazing day Bro XD XD XD

**Comment by iAmMe27** [comment]
Glad its solved 👍
