### ISSUE TITLE
Missing File (xLODgen.94.7z)

### ISSUE THREAD

**Issue by Ynomaq** [iAmMe27/WoD#8]
Hi there! Sorry to bother, but I'm unable to complete the installation of WoD... Wabbajack has a problem with a missing file: it should be 

xLODgen.94.7z

in the authored files on Wabbajack.

Thank you for your work! :)

**Comment by iAmMe27** [comment]
I am aware of this issue, it’s knocked out both of my modlists as well as numerous other modlists.

I am currently on a break and not able to immediately compile but I’ll leave this issue open as a reminder.

**Comment by Ynomaq** [comment]
Wow, You're fast! xD

Thank you very much, enjoy your break! ;)

**Comment by Ynomaq** [comment]
... I was wondering: is it possible to only share the file here on the wiki, like the other "difficult" ones? I don't want to be annoying, I don't know if it's complicated or not.

Thanx again for your patience and your work, 

Kind regards

**Comment by iAmMe27** [comment]
If you’re in the Discord server, I’m pretty sure an alternative link has been shared there

**Comment by Ynomaq** [comment]
I tried to, but it wouldn't let me in! xD I don't know why, Discord doesn't let me accept the invite to the server! Trying it again now...

**Comment by NeartLawt7** [comment]
can you shre the file here hit into same issus
Unable to download xLODGen.94.7z (WabbajackCDNDownloader+State|https://authored-files.wabbajack.org/xLODGen.94.7z_f3881fe6-a5d9-4a88-b85d-b2a2d7a88d03)
