### ISSUE TITLE
 temp glass window file error|| hashing error

### ISSUE THREAD

**Issue by tritiumexp** [iAmMe27/WoD#9]
the temp glass window texture i have on a new install seems to be the wrong hash, this causes the install to fail, 

the error is attached
![errron](https://github.com/iAmMe27/WoD/assets/133578618/e9c4131c-55d9-46e4-881e-665f3357b79d)

**Comment by iAmMe27** [comment]
If the install finished, then there is no longer an issue with the installation. This is also not a WoD issue but a Wabbajack one.

**Comment by tritiumexp** [comment]
> If the install finished, then there is no longer an issue with the installation. This is also not a WoD issue but a Wabbajack one.

so ive recently checked, and it causes the install to not finish, where the launcher is usualy instanced, this isnt, i am currently kinda fixing, by manualy creating a new mo2 instance, does this list change any of the folowing?: fallout4.ini , fallout4prefs.ini , or , fallout4custom.ini ? also i seem to be missing the plugins.txt, and modlist.txt for the profiles. managed to instal the mods with this though

**Comment by tritiumexp** [comment]
> If the install finished, then there is no longer an issue with the installation. This is also not a WoD issue but a Wabbajack one.

thanks

**Comment by tritiumexp** [comment]
updated, and overwrote install, fixed the innital issue, now the concrete window bsa wont build lol

**Comment by tritiumexp** [comment]
now bay window metal

**Comment by tritiumexp** [comment]
ran install again without overwrite this time and it successfully built

install went as follows
innitial install: just did the basics with wabbajack 3.0.4, no overwrite
fail at hashing check
second install: installed from disc with overwrite checked: wabbajack 3.1.0
third install: installed from disc with overwrite unchecked: wabbajack 3.1.0
sucess
